name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install uv ruff pytest
          make install
      - name: Run lint
        run: |
          make lint
      - name: Run test
        run: |
          make test
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: 811ab216404312db2a577bb7f2fa17f7674836d8f89f26e68772bab075e82270
        with:
          coverageCommand: make test-coverage
          debug: true
